name: run-code-checks

on:
  push:
  workflow_dispatch:

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up Python 🐍
        uses: actions/setup-python@v5
        with:
          cache: pip

      - name: Install dependencies 📦️
        run: |
          pip install --upgrade pip
          pip install -r requirements/requirements-dev.txt
          pip install -e .

      - name: Lint 🧹
        run: ruff check

      - name: Run unit tests 🧪
        run: |
          pytest -k unit

