name: run-code-checks

on:
  push:
  workflow_dispatch:

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Build Docker image 🐳
        run: |
          docker build -t virus-clade-utils .

      - name: lint 🧹
        run: |
          docker run --entrypoint /bin/bash virus-clade-utils \
          -c "ruff check"

      - name: run unit tests 🧪
        run: |
          docker run --entrypoint /bin/bash virus-clade-utils \
          -c "pytest -k unit"
