name: run-integration-tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Build Docker image 🐳
        run: |
          docker build -t virus-clade-utils .

      - name: run integration tests 🧪
        run: |
          docker run --entrypoint /bin/bash virus-clade-utils \
          -c "pytest -k integration"
